# Generated by Django 6.0.5 on 2026-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar number of the missing person (if known)', max_length=12),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='filer_contact',
            field=models.CharField(default=0, help_text='Your contact number', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missingperson',
            name='filer_email',
            field=models.EmailField(blank=True, help_text='Your email address (optional, for coordination)', max_length=254),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='relation',
            field=models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('SPOUSE', 'Spouse'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('RELATIVE', 'Other Relative'), ('FRIEND', 'Friend'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], default=0, help_text='Your relation to the missing person', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseupdate',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='clothing_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='fir_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='identifying_marks',
            field=models.TextField(blank=True),
        ),
    ]
