# Generated by Django 6.0.5 on 2026-09-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_missingperson_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='eye_color',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='filer_contact',
            field=models.CharField(help_text='Your contact number', max_length=10),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='fir_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='hair_color',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='last_seen_location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='police_station_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='relation',
            field=models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('SPOUSE', 'Spouse'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('RELATIVE', 'Relative'), ('FRIEND', 'Friend'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], help_text='Your relation to the missing person', max_length=20),
        ),
    ]
