# Generated by Django 4.2.30 on 2026-05-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khojuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='khojuser_set', related_query_name='khojuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='khojuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='khojuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='khojuser_set', related_query_name='khojuser', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
