# Generated by Django 6.0.5 on 2026-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_khojuser_groups_alter_khojuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='emergency_contact',
            field=models.CharField(max_length=10),
        ),
    ]
