# Generated by Django 6.0.5 on 2026-05-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='score_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
