# Generated by Django 6.0.5 on 2026-05-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedpatient',
            name='clothing_description',
            field=models.TextField(default='Unknown', help_text='Clothing worn when found - helps with matching'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidentifiedpatient',
            name='found_id_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of the ID number only', max_length=4),
        ),
        migrations.AddField(
            model_name='unidentifiedpatient',
            name='found_id_type',
            field=models.CharField(blank=True, choices=[('', 'No ID Found'), ('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('VOTER', 'Voter ID'), ('DRIVING', 'Driving Licence'), ('PASSPORT', 'Passport'), ('OTHER', 'Other ID')], default='', help_text='Type of ID found on the person (if any)', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidentifiedpatient',
            name='condition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unidentifiedpatient',
            name='estimated_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='unidentifiedpatient',
            name='identifying_marks',
            field=models.TextField(blank=True),
        ),
    ]
